[Match]
Profiles=nvidia
Profiles=kernel-lts
Distribution=arch
[Content]
Packages=
    lib32-nvidia-utils
    nvidia-open-lts
    nvidia-utils
    nvidia-settings
    nvidia-container-toolkit
    nvidia-prime

[Match]
Profiles=nvidia
Profiles=kernel-rolling
Distribution=arch
[Content]
Packages=
    lib32-nvidia-utils
    nvidia-open
    nvidia-utils
    nvidia-settings
    nvidia-container-toolkit
    nvidia-prime