---
name: Build latest images
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "05 10 * * *" # 10:05am UTC everyday
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - "**/CONTRIBUTING.md"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  apollo:
    name: apollo
    uses: ./.github/workflows/build-bootc-image.yaml
    with:
      image-name: "apollo"
      image-tag: "latest"
      profiles: "kernel-rolling"
    secrets: inherit

  apollo-lts:
    name: apollo-lts
    uses: ./.github/workflows/build-bootc-image.yaml
    with:
      image-name: "apollo-lts"
      image-tag: "latest"
      profiles: "kernel-lts"
    secrets: inherit

  apollo-nvidia-lts:
    name: apollo-nvidia-lts
    uses: ./.github/workflows/build-bootc-image.yaml
    with:
      image-name: "apollo-nvidia-lts"
      image-tag: "latest"
      profiles: "nvidia kernel-lts"
    secrets: inherit

  apollo-nvidia:
    name: apollo-nvidia
    uses: ./.github/workflows/build-bootc-image.yaml
    with:
      image-name: "apollo-nvidia"
      image-tag: "latest"
      profiles: "nvidia kernel-rolling"
    secrets: inherit
