---
name: Build container image
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "05 10 * * *" # 10:05am UTC everyday
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - "**/CONTRIBUTING.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-apollo:
    name: Build 'apollo'
    uses: ./.github/workflows/reusable-build.yml
    with:
      image-name: "apollo"
      image-tag: "latest"
